export declare const PI_COMPACTION_TOOLS_REQUIRED_VERSION: "0.85.1";
export declare const PI_COMPACTION_TOOLS_RUNTIME_TARGETS: readonly string[];
export declare const PI_COMPACTION_TOOLS_TYPE_TARGETS: readonly string[];
export declare const PI_COMPACTION_TOOLS_PATCH_TARGETS: readonly string[];
export declare const PI_COMPACTION_TOOLS_PATCH_MARKERS: Readonly<{
	request: string;
	historyResponse: string;
	prefixResponse: string;
	branchResponse: string;
	summaryFailure: string;
	summaryFailureTypes: string;
	contextBudgets: string;
	contextCallers: string;
	contextBudgetTypes: string;
	branchRequestBudget: string;
	branchHistoryCapacity: string;
	summaryIntegrity: string;
	branchIntegrity: string;
	summaryIntegrityTypes: string;
}>;
export declare function assertPiCompactionToolsPatchedSource(relativePath: string, source: string): void;
export declare function patchPiCompactionToolsSource(relativePath: string, source: string): string;
